-- 自動生成ファイル。直接編集せず scripts/generate-d1-seed.mjs を実行して作り直すこと。
-- 生成元: src/data/operatorCustomers.ts, src/data/mockData.ts, src/data/essentialOils.ts

delete from hearing_sheets; delete from aroma_ingredients; delete from favorites;
delete from aroma_records; delete from brainwave_images;
delete from base_blend_private_recipes; delete from base_blends;
delete from essential_oils; delete from mood_categories;
delete from profiles; delete from stores;

-- 店舗台帳
insert or ignore into stores (id, store_code, name) values ('store-ginza', '001', '銀座店');

-- 事業者側の顧客マスタ
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-sakura', 'user-sakura', 'store-ginza', 'store-ginza', '2600001', '田中 さくら', 'たなか さくら', 'customer', '["リラックス系","ウッディ系"]', '["夜","就寝前"]', '2026-01-12T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-ren', 'user-ren', 'store-ginza', 'store-ginza', '2600002', '佐藤 蓮', 'さとう れん', 'customer', '["集中系","ミント系"]', '["朝","仕事前"]', '2026-01-28T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-mika', 'user-mika', 'store-ginza', 'store-ginza', '2600003', '鈴木 美香', 'すずき みか', 'customer', '["フローラル系","バランス系"]', '["夕方","入浴後"]', '2026-02-08T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-haruto', 'user-haruto', 'store-ginza', 'store-ginza', '2600004', '高橋 陽斗', 'たかはし はると', 'customer', '["シトラス系","リフレッシュ系"]', '["昼","外出前"]', '2026-02-19T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-natsumi', 'user-natsumi', 'store-ginza', 'store-ginza', '2600005', '中村 夏美', 'なかむら なつみ', 'customer', '["ハーバル系","睡眠系"]', '["夜","休日"]', '2026-03-02T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-naoto', 'user-naoto', 'store-ginza', 'store-ginza', '2600006', '小林 直人', 'こばやし なおと', 'customer', '["森林系","集中系"]', '["朝","作業前"]', '2026-03-14T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-eriko', 'user-eriko', 'store-ginza', 'store-ginza', '2600007', '伊藤 恵理子', 'いとう えりこ', 'customer', '["樹脂系","落ち着き系"]', '["夕方","瞑想前"]', '2026-03-27T00:00:00.000Z');
insert or ignore into profiles (id, user_id, store_id, origin_store_id, customer_number, name, name_kana, role, favorite_types, frequent_times, created_at) values ('profile-daichi', 'user-daichi', 'store-ginza', 'store-ginza', '2600008', '森田 大地', 'もりた だいち', 'customer', '["スパイス系","元気系"]', '["午前","運動前"]', '2026-04-05T00:00:00.000Z');

-- ベースブレンド
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-01', '①ブレンド', 'Elegant Harmony', '疲労回復・安眠効果をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["ラベンダー","オレンジスイート","ゼラニウム"]', '["疲労回復","安眠効果"]', '["relax","sleep"]', '#c7b5df');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-02', '②ブレンド', 'Woody Restore', '疲労回復・安眠効果をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["ローズマリー","コリアンダー","シダーウッド"]', '["疲労回復","安眠効果"]', '["relax","sleep"]', '#b89068');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-03', '③ブレンド', 'Golden Elixir', '肌の老化防止をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["フランキンセンス","サンダルウッド","パチュリ"]', '["肌の老化防止"]', '["relax"]', '#d0b894');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-04', '④ブレンド', 'Fresh Bloom', '肌の老化防止をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["パルマローザ","ゼラニウム","ティーツリー"]', '["肌の老化防止"]', '["happy","refresh"]', '#efb8c8');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-05', '⑤ブレンド', 'Serene Dreams', '不眠・緊張防止をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["スイートマジョラム","ラベンダー","イランイラン"]', '["不眠","緊張防止"]', '["sleep","relax"]', '#b8a6c8');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-07', '⑦ブレンド', 'Forest Harmony', 'リラックス・鎮静をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["シダーウッド","ラベンダー","ユーカリ"]', '["リラックス","鎮静"]', '["relax","refresh"]', '#9fc8bd');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-09', '⑨ブレンド', 'Mind Boost', '集中力向上・記憶力強化をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["ローズマリー","ユーカリ","ペパーミント"]', '["集中力向上","記憶力強化"]', '["focus","refresh"]', '#8fb98f');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-10', '⑩ブレンド', 'Citrus Sharp', '集中力向上・気分向上をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["レモン","オレンジスイート"]', '["集中力向上","気分向上"]', '["focus","energy","happy"]', '#f4c97c');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-12', '⑫ブレンド', 'Night Deep', '深い睡眠・安眠促進をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["ラベンダー","スイートマジョラム","スイートオレンジ"]', '["深い睡眠","安眠促進"]', '["sleep","relax"]', '#b7c3de');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-15', '⑮ブレンド', 'Power Boost', '疲労回復・スタミナ向上をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["ローズマリー","ユーカリ","ジュニパーベリー"]', '["疲労回復","スタミナ向上"]', '["energy","refresh"]', '#a7d7c5');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-16', '⑯ブレンド', 'Feminine Balance', 'ホルモンバランス調整・女性特有の悩みをテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["クラリセージ","パルマローザ","ラベンダー"]', '["ホルモンバランス調整","女性特有の悩み"]', '["relax","happy"]', '#d9b4a8');
insert or ignore into base_blends (id, code, name, description, public_ingredients, benefits, mood_slugs, color) values ('base-17', '⑰ブレンド', 'Woman Care', '女性の健康・美容・自信向上をテーマにしたベースブレンド。公開画面では配合比率を表示しません。', '["ゼラニウム","イランイラン","スイートオレンジ"]', '["女性の健康","美容","自信向上"]', '["happy","relax"]', '#e7b8c4');

-- 一般精油
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-lavender', 'lavender', 'ラベンダー', 'Lavandula angustifolia', 'シソ科', 'ミドル', 'フローラル、ハーバル、やや甘い', 'やわらかく親しみやすい香り。夜のリラックスタイムや落ち着きたい場面でよく選ばれます。', '["就寝前の芳香浴","緊張をゆるめたい時間","フローラル系ブレンドの中心"]', '["relax","sleep"]', '["スイートオレンジ","ベルガモット","フランキンセンス","ゼラニウム"]', '一般的には扱いやすい精油ですが、肌に使う場合は希釈し、違和感があれば中止してください。', '#c7b5df');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-sweet-orange', 'sweet-orange', 'スイートオレンジ', 'Citrus sinensis', 'ミカン科', 'トップ', '甘い柑橘、明るい、親しみやすい', '明るく丸みのある柑橘の香り。気分を軽くしたい時や、ブレンドをやさしくまとめたい時に便利です。', '["朝の芳香浴","気分転換","フローラルやハーブの角を丸める"]', '["energy","happy","refresh"]', '["ラベンダー","ゼラニウム","シダーウッド","クローブ"]', '柑橘精油は種類や抽出方法で光毒性の扱いが変わります。肌使用時は製品情報を確認してください。', '#f4c97c');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-bergamot', 'bergamot', 'ベルガモット', 'Citrus bergamia', 'ミカン科', 'トップ', '上品な柑橘、ほろ苦い、紅茶のよう', '柑橘の軽さと大人っぽい苦みがある香り。リラックス系にも前向きな気分づくりにも合わせやすい精油です。', '["夕方の切り替え","落ち着いた柑橘ブレンド","上品な香りづくり"]', '["relax","happy","sleep"]', '["ラベンダー","クラリセージ","フランキンセンス","イランイラン"]', 'ベルガモットなど一部柑橘精油は光毒性に注意が必要です。肌使用後の紫外線曝露は避けてください。', '#e6c77e');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-frankincense', 'frankincense', 'フランキンセンス', 'Boswellia carterii', 'カンラン科', 'ベース', '樹脂、静か、ほのかにスパイシー', '深呼吸したくなるような樹脂の香り。静かな時間や瞑想的なブレンドに奥行きを出します。', '["夜のリラックス","呼吸を整えたい時間","香りに余韻を出す"]', '["relax","sleep"]', '["ラベンダー","ベルガモット","サンダルウッド","ミルラ"]', '樹脂系は重く残りやすいため、少量から調整してください。', '#d0b894');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-peppermint', 'peppermint', 'ペパーミント', 'Mentha piperita', 'シソ科', 'トップ', '清涼感、ミント、シャープ', 'すっきりとした清涼感のある香り。朝や作業前の切り替えに少量使うと印象が引き締まります。', '["集中したい時","リフレッシュ","重い香りの引き締め"]', '["focus","refresh"]', '["レモン","ローズマリー","ユーカリ","ラベンダー"]', '刺激を感じやすい精油です。子どもや妊娠中、持病がある場合の使用は専門家に確認してください。', '#a7d7c5');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-rosemary', 'rosemary', 'ローズマリー', 'Salvia rosmarinus', 'シソ科', 'ミドル', 'ハーバル、クリア、すっきり', 'シャープなハーブ感があり、作業前や朝のブレンドに向きます。柑橘やミントと相性が良い香りです。', '["作業前","朝のルーティン","クリアな印象づくり"]', '["focus","refresh"]', '["レモン","ペパーミント","ユーカリ","グレープフルーツ"]', '刺激を感じる場合があります。高濃度や長時間使用は避けてください。', '#8fb98f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-lemon', 'lemon', 'レモン', 'Citrus limon', 'ミカン科', 'トップ', '爽やか、軽い、フレッシュ', '明るく清潔感のある柑橘の香り。集中やリフレッシュ系のトップノートとして使いやすい精油です。', '["朝の空間づくり","集中前","すっきりした印象"]', '["focus","refresh"]', '["ペパーミント","ローズマリー","ティートリー","ジュニパーベリー"]', '圧搾レモンは光毒性に注意が必要です。肌使用時は製品仕様を確認してください。', '#f0d36b');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-eucalyptus', 'eucalyptus', 'ユーカリ', 'Eucalyptus globulus', 'フトモモ科', 'トップ', 'クリア、カンファー、森林感', 'すっと抜けるような清涼感。呼吸を深くしたい気分の芳香浴やリフレッシュ系によく合います。', '["リフレッシュ","清潔感のある空間","ミント系ブレンド"]', '["refresh","focus"]', '["ペパーミント","ローズマリー","レモン","ティートリー"]', '乳幼児の顔まわりでは避けるなど、年齢や体調に応じた安全確認が必要です。', '#9fc8bd');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-tea-tree', 'tea-tree', 'ティートリー', 'Melaleuca alternifolia', 'フトモモ科', 'ミドル', 'グリーン、薬草調、清潔感', '清潔感のあるシャープな香り。単独よりも柑橘やハーブと合わせると使いやすくなります。', '["空間をすっきりさせたい時","リフレッシュ","ハーバルブレンド"]', '["refresh","focus"]', '["レモン","ユーカリ","ラベンダー","ローズマリー"]', '肌刺激を感じる場合があります。必ず希釈し、酸化した古い精油は避けてください。', '#8fbf9f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-geranium', 'geranium', 'ゼラニウム', 'Pelargonium graveolens', 'フウロソウ科', 'ミドル', 'ローズ調、グリーン、甘い', '花らしさとグリーン感のバランスが良い香り。フローラル系をやさしく整えます。', '["気分を上げたい時","バランス感のある香り","女性らしい印象"]', '["relax","happy"]', '["ラベンダー","ベルガモット","クラリセージ","パチュリ"]', '香りが強く出やすいため少量から調整してください。', '#efb8c8');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-ylang-ylang', 'ylang-ylang', 'イランイラン', 'Cananga odorata', 'バンレイシ科', 'ミドル', '濃厚な花、甘い、エキゾチック', '甘く華やかで存在感のある香り。リラックス系や特別感のあるブレンドに少量加えると印象が出ます。', '["夜のリラックス","華やかさを足す","甘いフローラル"]', '["relax","happy"]', '["ベルガモット","オレンジ","サンダルウッド","ゼラニウム"]', '濃厚で頭重感を覚える場合があります。少量から使ってください。', '#e7b8c4');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-clary-sage', 'clary-sage', 'クラリセージ', 'Salvia sclarea', 'シソ科', 'ミドル', 'ハーバル、甘い、ややナッティ', '落ち着いた甘さのあるハーブ調。夜やくつろぎのブレンドに深みを加えます。', '["落ち着きたい時","フローラルの調整","大人っぽい香り"]', '["relax","sleep"]', '["ベルガモット","ラベンダー","ゼラニウム","シダーウッド"]', '妊娠中や飲酒時などは使用を控える判断が必要です。', '#b8a6c8');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-cedarwood', 'cedarwood', 'シダーウッド', 'Cedrus atlantica', 'マツ科', 'ベース', 'ウッディ、乾いた木、落ち着き', '穏やかな木の香り。ブレンドに安定感を出し、甘い香りを引き締めます。', '["夜の落ち着き","ウッディ調","香りの土台づくり"]', '["relax","sleep","focus"]', '["オレンジ","ラベンダー","ローズマリー","フランキンセンス"]', '重くなりやすいので、トップノートと合わせて少量から調整してください。', '#b89068');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-sandalwood', 'sandalwood', 'サンダルウッド', 'Santalum album', 'ビャクダン科', 'ベース', 'なめらか、ウッディ、クリーミー', 'なめらかで静かな木の香り。余韻が長く、瞑想的なブレンドや高級感の演出に向きます。', '["深いリラックス","香りの余韻","高級感のあるブレンド"]', '["relax","sleep"]', '["フランキンセンス","イランイラン","ベルガモット","ローズ"]', '希少性が高い精油です。由来や品質表示を確認してください。', '#c0a076');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-patchouli', 'patchouli', 'パチュリ', 'Pogostemon cablin', 'シソ科', 'ベース', '土っぽい、甘い、重厚', '個性的で深い土っぽさのある香り。少量でブレンドに奥行きと持続性を加えます。', '["香りの固定","落ち着いた印象","個性的なブレンド"]', '["relax"]', '["ゼラニウム","ベルガモット","サンダルウッド","クラリセージ"]', '非常に存在感が強いため、1滴未満の感覚で少量から調整してください。', '#9b7b5b');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-grapefruit', 'grapefruit', 'グレープフルーツ', 'Citrus paradisi', 'ミカン科', 'トップ', 'ほろ苦い柑橘、軽快、明るい', '軽やかでほろ苦い柑橘の香り。朝や気分転換のブレンドにフレッシュさを足します。', '["朝の気分転換","軽やかな柑橘","リフレッシュ"]', '["energy","happy","refresh"]', '["ローズマリー","ペパーミント","ジュニパーベリー","ゼラニウム"]', '圧搾グレープフルーツは光毒性に注意が必要です。肌使用時は確認してください。', '#f2bf7a');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-lime', 'lime', 'ライム', 'Citrus aurantifolia', 'ミカン科', 'トップ', '鋭い柑橘、爽快、軽い甘さ', 'キレのある爽快な柑橘。甘い香りを軽くしたい時や、リフレッシュ感を出す時に使いやすい精油です。', '["リフレッシュ","明るい印象づくり","甘さの調整"]', '["energy","happy","refresh"]', '["ペパーミント","ジンジャー","レモングラス","シダーウッド"]', '圧搾ライムは光毒性に注意。蒸留品など製品仕様を確認してください。', '#c9d86f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-mandarin', 'mandarin', 'マンダリン', 'Citrus reticulata', 'ミカン科', 'トップ', 'やさしい柑橘、甘い、軽い', '甘くやさしい柑橘の香り。強い香りが苦手な人にも使いやすく、夜の柑橘ブレンドにも向きます。', '["穏やかな気分転換","家族向けの空間","やさしい甘さ"]', '["relax","happy"]', '["ラベンダー","カモミール","ネロリ","フランキンセンス"]', '柑橘精油として、肌使用時は製品の光毒性情報を確認してください。', '#f0b66f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-lemongrass', 'lemongrass', 'レモングラス', 'Cymbopogon citratus', 'イネ科', 'トップ', 'レモン様、草、力強い', 'レモンに似た強い草の香り。空間をすっきりさせたい時に少量使うと印象が変わります。', '["リフレッシュ","空間の切り替え","シャープな印象"]', '["refresh","energy"]', '["ライム","ジンジャー","ペパーミント","シダーウッド"]', '刺激が強めです。肌使用では低濃度にし、敏感肌は注意してください。', '#c6ca72');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-chamomile-roman', 'chamomile-roman', 'ローマンカモミール', 'Chamaemelum nobile', 'キク科', 'ミドル', 'リンゴ様、甘い、穏やか', '甘くやさしいハーブ調。夜のリラックスブレンドに丸みを与えます。', '["就寝前","穏やかな香り","やさしいハーブ調"]', '["relax","sleep"]', '["ラベンダー","マンダリン","クラリセージ","サンダルウッド"]', 'キク科に敏感な方は注意してください。', '#e8d799');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-rose', 'rose', 'ローズ', 'Rosa damascena', 'バラ科', 'ミドル', '華やか、濃厚、上品', '少量で華やかさが出る高級感のある香り。フローラルブレンドの印象を大きく変えます。', '["特別感のある香り","気分を上げたい時","フローラルの主役"]', '["happy","relax"]', '["サンダルウッド","ベルガモット","ゼラニウム","ネロリ"]', '高価で濃厚な香りです。少量から使い、品質表示を確認してください。', '#df9aae');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-neroli', 'neroli', 'ネロリ', 'Citrus aurantium var. amara', 'ミカン科', 'ミドル', '白い花、柑橘、上品', 'ビターオレンジの花から得られる上品な香り。落ち着きと明るさを両立したいブレンドに合います。', '["夜のケア時間","上品なフローラル","気分の切り替え"]', '["relax","happy"]', '["ラベンダー","ベルガモット","サンダルウッド","マンダリン"]', '香りが繊細なので、強い精油と合わせる時は量を控えめにしてください。', '#f2d7bc');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-jasmine', 'jasmine', 'ジャスミン', 'Jasminum grandiflorum', 'モクセイ科', 'ミドル', '濃厚な花、甘い、官能的', '甘く濃厚な白花の香り。ごく少量で華やかさと深みを加えます。', '["気分を上げたい時","特別なブレンド","甘いフローラル"]', '["happy","relax"]', '["ベルガモット","サンダルウッド","ローズ","オレンジ"]', '強く香るため少量から調整してください。妊娠中などは専門家に確認してください。', '#e7c0d2');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-palmarosa', 'palmarosa', 'パルマローザ', 'Cymbopogon martinii', 'イネ科', 'ミドル', 'ローズ調、草、軽い甘さ', 'ローズに似た明るい草花の香り。フローラルを軽くしたい時に使いやすい精油です。', '["バランスの良い香り","軽いフローラル","気分転換"]', '["relax","happy"]', '["ゼラニウム","ラベンダー","ベルガモット","シダーウッド"]', '香りが広がりやすいため、少量から調整してください。', '#d9b4a8');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-juniper-berry', 'juniper-berry', 'ジュニパーベリー', 'Juniperus communis', 'ヒノキ科', 'ミドル', '森林、ドライ、すっきり', 'ドライで透明感のある森林調。リフレッシュやウッディ系ブレンドの橋渡しに使いやすい香りです。', '["リフレッシュ","森林感","ドライな印象"]', '["refresh","focus"]', '["グレープフルーツ","ローズマリー","シダーウッド","ラベンダー"]', '持病や妊娠中など体調に不安がある場合は専門家に確認してください。', '#9aae9d');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-cypress', 'cypress', 'サイプレス', 'Cupressus sempervirens', 'ヒノキ科', 'ミドル', '針葉樹、ドライ、端正', 'すっきりとした針葉樹の香り。甘さを抑えた落ち着いたブレンドに向きます。', '["呼吸を整えたい気分","森林調","端正な印象"]', '["refresh","relax"]', '["ベルガモット","ジュニパーベリー","ラベンダー","フランキンセンス"]', '香りがドライに出やすいため、柑橘や花と合わせると使いやすくなります。', '#8ea28f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-hinoki', 'hinoki', 'ヒノキ', 'Chamaecyparis obtusa', 'ヒノキ科', 'ベース', '和の木、落ち着き、清潔感', '日本らしい木の香り。深呼吸したくなる空間や、落ち着いた和の印象づくりに合います。', '["落ち着いた空間","深呼吸","和のブレンド"]', '["relax","refresh"]', '["ユーカリ","フランキンセンス","ベルガモット","ラベンダー"]', '木部・枝葉など部位で香りが異なるため、製品ごとの印象を確認してください。', '#b99f78');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-ginger', 'ginger', 'ジンジャー', 'Zingiber officinale', 'ショウガ科', 'ミドル', '温かい、スパイシー、ドライ', '温かみのあるスパイス調。柑橘と合わせると元気な印象のブレンドになります。', '["元気を出したい時","温かい印象","スパイスアクセント"]', '["energy","refresh"]', '["オレンジ","ライム","レモングラス","シダーウッド"]', '刺激を感じる場合があるため、肌使用では低濃度から確認してください。', '#c79a67');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-black-pepper', 'black-pepper', 'ブラックペッパー', 'Piper nigrum', 'コショウ科', 'ミドル', 'スパイシー、温かい、ドライ', 'ピリッとした温かみのある香り。重いウッディや柑橘にアクセントを加えます。', '["元気な印象","温かみ","アクセント"]', '["energy","focus"]', '["グレープフルーツ","ローズマリー","フランキンセンス","ジンジャー"]', '刺激が出る場合があります。少量から使用してください。', '#8a7668');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-basil', 'basil', 'バジル', 'Ocimum basilicum', 'シソ科', 'ミドル', 'ハーバル、甘さ、スパイス感', '甘さのあるハーブ調。集中系ブレンドにやわらかな奥行きを加えます。', '["作業前","ハーバルブレンド","気分転換"]', '["focus","refresh"]', '["レモン","ローズマリー","ラベンダー","ペパーミント"]', '種類により成分が異なります。妊娠中や持病がある場合は専門家に確認してください。', '#8bad75');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-marjoram', 'marjoram', 'マジョラム', 'Origanum majorana', 'シソ科', 'ミドル', '温かいハーブ、やさしい、少しスパイシー', '温かみのある穏やかなハーブ調。夜のリラックスブレンドにやさしさを足します。', '["夜のくつろぎ","温かい印象","ハーバル調"]', '["relax","sleep"]', '["ラベンダー","ベルガモット","シダーウッド","クラリセージ"]', '眠気を感じる場合があるため、車の運転前などは避けてください。', '#b8b47c');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-vetiver', 'vetiver', 'ベチバー', 'Vetiveria zizanoides', 'イネ科', 'ベース', '土、根、重厚、スモーキー', '深く重い根の香り。香りの土台や静かな夜のブレンドにごく少量使います。', '["深い落ち着き","香りの固定","重厚感"]', '["relax","sleep"]', '["ラベンダー","サンダルウッド","ベルガモット","フランキンセンス"]', '非常に重く残るため、少量から調整してください。', '#8b735f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-myrrh', 'myrrh', 'ミルラ', 'Commiphora myrrha', 'カンラン科', 'ベース', '樹脂、ほろ苦い、静か', 'ほろ苦く静かな樹脂の香り。フランキンセンスと合わせると奥行きのある印象になります。', '["静かな時間","樹脂系ブレンド","余韻づくり"]', '["relax"]', '["フランキンセンス","サンダルウッド","ベルガモット","ラベンダー"]', '粘度が高い場合があります。ディフューザーや器具の仕様に注意してください。', '#a98265');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-clove', 'clove', 'クローブ', 'Syzygium aromaticum', 'フトモモ科', 'ミドル', '甘いスパイス、温かい、強い', '甘く強いスパイス調。冬らしい香りや柑橘ブレンドに少量で温かみを加えます。', '["温かい香り","アクセント","季節感"]', '["energy"]', '["オレンジ","シナモン","ジンジャー","シダーウッド"]', '刺激が強い精油です。肌使用は特に低濃度で、敏感肌は避ける判断も必要です。', '#9b654c');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-cinnamon-leaf', 'cinnamon-leaf', 'シナモンリーフ', 'Cinnamomum zeylanicum', 'クスノキ科', 'ミドル', '甘いスパイス、温かい、濃厚', '甘く温かいスパイスの香り。柑橘やウッディと合わせると季節感が出ます。', '["温かみ","冬のブレンド","少量アクセント"]', '["energy","happy"]', '["オレンジ","クローブ","ジンジャー","フランキンセンス"]', '刺激が強いため、肌使用は慎重に。少量から調整してください。', '#b16f4f');
insert or ignore into essential_oils (id, slug, name, botanical_name, family, scent_note, scent_profile, overview, common_uses, mood_slugs, blends_well_with, safety_note, color) values ('oil-spearmint', 'spearmint', 'スペアミント', 'Mentha spicata', 'シソ科', 'トップ', 'やさしいミント、甘い、軽い', 'ペパーミントよりやわらかいミント調。軽い清涼感を出したい時に使いやすい精油です。', '["軽いリフレッシュ","朝の香り","ミントの調整"]', '["refresh","focus"]', '["レモン","ラベンダー","ローズマリー","グレープフルーツ"]', 'ミント系として刺激に注意し、少量から使ってください。', '#9fd0b6');

-- 気分カテゴリ
insert or ignore into mood_categories (id, slug, name, description, image_url, color, icon) values ('m1', 'relax', 'リラックスしたい', 'ゆっくり休みたい夜に', null, 'from-[#c7b5df] to-[#f5d7d6]', 'Moon');
insert or ignore into mood_categories (id, slug, name, description, image_url, color, icon) values ('m2', 'sleep', 'よく眠りたい', '眠る前の深呼吸に', null, 'from-[#b7c3de] to-[#e8dcf4]', 'Sparkles');
insert or ignore into mood_categories (id, slug, name, description, image_url, color, icon) values ('m3', 'focus', '集中したい', '作業前の切り替えに', null, 'from-[#b8d7c0] to-[#f3e5b6]', 'Target');
insert or ignore into mood_categories (id, slug, name, description, image_url, color, icon) values ('m4', 'energy', '元気になりたい', '朝や外出前に', null, 'from-[#f4c97c] to-[#f6dccf]', 'Sun');
insert or ignore into mood_categories (id, slug, name, description, image_url, color, icon) values ('m5', 'happy', '気分を上げたい', '軽やかに過ごしたい日に', null, 'from-[#efb8c8] to-[#f6e0a6]', 'Heart');
insert or ignore into mood_categories (id, slug, name, description, image_url, color, icon) values ('m6', 'refresh', 'リフレッシュしたい', 'すっきり整えたい時に', null, 'from-[#a7d7c5] to-[#d9e9f0]', 'Wind');


-- 制作記録（カルテ）
insert or ignore into aroma_records (id, user_id, blend_lot_number, base_blend_id, base_blend_name, base_blend_volume_ml, title, subtitle, concept, mood, purpose, blend_notes, usage_notes, caution_notes, total_volume_ml, reorder_url, price, volume, status, made_at) values ('relax-night', 'user-sakura', 'AR-2026-0508-YK01', 'base-01', 'Elegant Harmony', 9, 'Relax Night Blend', '心を落ち着ける夜のブレンド', '眠る前の呼吸をゆるめる、やわらかなラベンダー調。', 'リラックス', '安眠', 'Elegant Harmony 9mlに、ラベンダー・スイートオレンジ・フランキンセンスを添加した記録です。', '就寝30分前、手首やデコルテに少量をなじませてください。', '肌に異常がある場合は使用を避け、妊娠中は専門家に相談してください。', null, 'https://example.com/products/relax-night', 4200, '10ml', 'published', '2026-05-08');
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i1', 'relax-night', 'ラベンダー', '3', '滴', 1);
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i2', 'relax-night', 'スイートオレンジ', '2', '滴', 2);
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i3', 'relax-night', 'フランキンセンス', '1', '滴', 3);
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i4', 'relax-night', 'ベルガモット', '1', '滴', 4);
insert or ignore into aroma_records (id, user_id, blend_lot_number, base_blend_id, base_blend_name, base_blend_volume_ml, title, subtitle, concept, mood, purpose, blend_notes, usage_notes, caution_notes, total_volume_ml, reorder_url, price, volume, status, made_at) values ('morning-refresh', 'user-sakura', 'AR-2026-0418-YK02', 'base-10', 'Citrus Sharp', 8, 'Morning Refresh', '朝の集中を整えるクリアな香り', '軽いシトラスとミントで、朝のスイッチを入れるブレンド。', 'リフレッシュ', '集中', 'Citrus Sharp 8mlに、レモン・ペパーミント・ローズマリーを添加した記録です。', '朝の身支度前に、首元から少し離して香りを確認してください。', '光毒性に注意し、塗布後すぐの日光曝露は避けてください。', null, 'https://example.com/products/morning-refresh', 3900, '10ml', 'published', '2026-04-18');
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i6', 'morning-refresh', 'レモン', '2', '滴', 1);
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i7', 'morning-refresh', 'ペパーミント', '1', '滴', 2);
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i8', 'morning-refresh', 'ローズマリー', '1', '滴', 3);
insert or ignore into aroma_records (id, user_id, blend_lot_number, base_blend_id, base_blend_name, base_blend_volume_ml, title, subtitle, concept, mood, purpose, blend_notes, usage_notes, caution_notes, total_volume_ml, reorder_url, price, volume, status, made_at) values ('focus-clear', 'user-ren', 'AR-2026-0402-ST01', 'base-09', 'Mind Boost', 10, 'Focus Clear Blend', '思考をすっきり整えるブレンド', '作業前に使いやすい、ハーバルで透明感のある香り。', '集中', '思考サポート', 'ローズマリーとユーカリを中心に軽く仕上げています。', 'デスク周りで深呼吸しながら香りを楽しんでください。', '乳幼児の近くでの使用は控えてください。', null, 'https://example.com/products/focus-clear', 4100, '10ml', 'published', '2026-04-02');
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i9', 'focus-clear', 'ローズマリー', '2', '滴', 1);
insert or ignore into aroma_records (id, user_id, blend_lot_number, base_blend_id, base_blend_name, base_blend_volume_ml, title, subtitle, concept, mood, purpose, blend_notes, usage_notes, caution_notes, total_volume_ml, reorder_url, price, volume, status, made_at) values ('happy-citrus', 'user-sakura', 'AR-2026-0329-YK03', 'base-15', 'Power Boost', 9, 'Happy Citrus', '前向きな気分に寄り添う柑橘ブレンド', '明るい甘さで気分を上げる午後の香り。', '元気', '前向き', 'オレンジ、グレープフルーツ、ゼラニウムを軽快に配合。', '外出前や休憩時に香りを確かめてください。', '敏感肌の方はパッチテストをしてください。', null, null, 3600, '10ml', 'published', '2026-03-29');
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i10', 'happy-citrus', 'スイートオレンジ', '3', '滴', 1);
insert or ignore into aroma_records (id, user_id, blend_lot_number, base_blend_id, base_blend_name, base_blend_volume_ml, title, subtitle, concept, mood, purpose, blend_notes, usage_notes, caution_notes, total_volume_ml, reorder_url, price, volume, status, made_at) values ('breath-deep', 'user-mika', 'AR-2026-0310-AY01', 'base-07', 'Forest Harmony', 10, 'Breath Deep Blend', '呼吸を整える静かなブレンド', '深呼吸したくなる森のような清涼感。', 'リフレッシュ', '呼吸を整える', 'ユーカリとヒノキを中心に、穏やかな余韻を残します。', '胸元から少し離して香りを吸い込んでください。', '喘息など呼吸器疾患がある方は医師に相談してください。', null, 'https://example.com/products/breath-deep', 4400, '10ml', 'published', '2026-03-10');
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i11', 'breath-deep', 'ユーカリ', '2', '滴', 1);
insert or ignore into aroma_records (id, user_id, blend_lot_number, base_blend_id, base_blend_name, base_blend_volume_ml, title, subtitle, concept, mood, purpose, blend_notes, usage_notes, caution_notes, total_volume_ml, reorder_url, price, volume, status, made_at) values ('floral-harmony', 'user-sakura', 'AR-2026-0220-YK04', 'base-16', 'Feminine Balance', 8, 'Floral Harmony', '女性らしさとバランスに寄り添う香り', '花の甘さを控えめに重ねた、穏やかな日常のブレンド。', '気分を上げたい', 'バランス', 'ゼラニウムとラベンダーをやわらかく調和させています。', '入浴後、手首に少量をなじませてください。', '使用中に違和感があればすぐ洗い流してください。', null, 'https://example.com/products/floral-harmony', 4600, '10ml', 'draft', '2026-02-20');
insert or ignore into aroma_ingredients (id, aroma_record_id, name, amount, unit, sort_order) values ('i12', 'floral-harmony', 'ゼラニウム', '2', '滴', 1);